import { chmod, writeFile } from "node:fs/promises";
import { existsSync } from "node:fs";
import { join } from "node:path";
import { DEFAULT_ROUTER_BASE_URL } from "./config.mjs";

export const WELCOME_BANNER = `
Welcome to Relay

0G has the models. Relay gives them one shared memory.

One task state across every model and CLI layer — compact handoffs,
better token efficiency, and no transcript replay when you switch.

Your keys stay on this machine (.env). Relay never uploads them.

Let's wire up your Router key and get you building.
`.trim();

export function envFilePath(projectRoot) {
  return join(projectRoot, ".env");
}

export function hasExistingEnv(projectRoot) {
  return existsSync(envFilePath(projectRoot));
}

export async function runOnboardingWizard(projectRoot, io) {
  io.stdout.write(`\n${WELCOME_BANNER}\n\n`);

  if (hasExistingEnv(projectRoot)) {
    const reconfigure = await promptYesNo(io, "Relay is already configured here. Reconfigure? [y/N] ", false);
    if (!reconfigure) {
      return { skipped: true };
    }
    io.stdout.write("\n");
  }

  const inferenceKey = await promptRequiredMasked(io, "Router inference key (hidden while you type):\n› ");
  io.stdout.write("\nLocked in.\n\n");

  const storageKey = await promptOptionalMasked(
    io,
    "Storage private key for publish / relay to (Enter to skip):\n› "
  );

  if (storageKey) {
    io.stdout.write("\nStorage configured.\n");
  } else {
    io.stdout.write("\nStorage skipped — add OG_STORAGE_PRIVATE_KEY to .env anytime.\n");
  }

  await writeProjectEnv(projectRoot, {
    OG_INFERENCE_API_KEY: inferenceKey,
    OG_STORAGE_PRIVATE_KEY: storageKey ?? ""
  });

  io.stdout.write("\nReady. Opening Relay…\n\n");

  return {
    skipped: false,
    values: {
      OG_INFERENCE_API_KEY: inferenceKey,
      OG_STORAGE_PRIVATE_KEY: storageKey ?? ""
    }
  };
}

export async function writeProjectEnv(projectRoot, values) {
  const lines = [
    "# Generated by relay init",
    "# 0G Compute Router (required for model calls)",
    `OG_ROUTER_BASE_URL=${values.OG_ROUTER_BASE_URL ?? DEFAULT_ROUTER_BASE_URL}`,
    `OG_INFERENCE_API_KEY=${values.OG_INFERENCE_API_KEY ?? ""}`,
    "",
    "# Optional management key for future account/balance commands.",
    `OG_MANAGEMENT_API_KEY=${values.OG_MANAGEMENT_API_KEY ?? ""}`,
    "",
    "# 0G Storage (required for publish/fetch and relay to)",
    `OG_STORAGE_NETWORK=${values.OG_STORAGE_NETWORK ?? "mainnet"}`,
    `OG_STORAGE_MODE=${values.OG_STORAGE_MODE ?? "turbo"}`,
    `OG_EVM_RPC_URL=${values.OG_EVM_RPC_URL ?? "https://evmrpc.0g.ai"}`,
    `OG_STORAGE_INDEXER_URL=${values.OG_STORAGE_INDEXER_URL ?? "https://indexer-storage-turbo.0g.ai"}`,
    `OG_STORAGE_PRIVATE_KEY=${values.OG_STORAGE_PRIVATE_KEY ?? ""}`,
    ""
  ];

  const path = envFilePath(projectRoot);
  await writeFile(path, lines.join("\n"), "utf8");

  try {
    await chmod(path, 0o600);
  } catch {
    // Best-effort on platforms that support it.
  }
}

export async function promptRequiredMasked(io, label) {
  while (true) {
    const value = await promptMasked(io, label);
    if (typeof value === "string" && value.trim()) {
      return value.trim();
    }
    io.stderr.write("A value is required.\n");
  }
}

export async function promptOptionalMasked(io, label) {
  const value = await promptMasked(io, label, { allowEmpty: true });
  if (!value || !value.trim()) {
    return null;
  }
  return value.trim();
}

export async function promptYesNo(io, label, defaultYes = false) {
  if (typeof io.promptLine === "function") {
    const answer = await io.promptLine(label);
    return parseYesNo(answer, defaultYes);
  }

  const answer = await readLineFromTty(label);
  return parseYesNo(answer, defaultYes);
}

export async function promptMasked(io, label, { allowEmpty = false } = {}) {
  if (typeof io.promptMasked === "function") {
    return io.promptMasked(label, { allowEmpty });
  }

  if (typeof io.promptLine === "function") {
    return io.promptLine(label, { allowEmpty });
  }

  return readMaskedFromTty(label, { allowEmpty });
}

function parseYesNo(answer, defaultYes) {
  const trimmed = typeof answer === "string" ? answer.trim().toLowerCase() : "";
  if (!trimmed) {
    return defaultYes;
  }
  return trimmed === "y" || trimmed === "yes";
}

async function readLineFromTty(label) {
  if (!process.stdin.isTTY) {
    return "";
  }

  const { createInterface } = await import("node:readline");
  const rl = createInterface({
    input: process.stdin,
    output: process.stdout,
    terminal: true
  });

  try {
    return await new Promise((resolve) => {
      rl.question(label, (answer) => resolve(answer));
    });
  } finally {
    rl.close();
  }
}

async function readMaskedFromTty(label, { allowEmpty = false } = {}) {
  if (!process.stdin.isTTY) {
    return "";
  }

  process.stdout.write(label);

  const stdin = process.stdin;
  const wasRaw = stdin.isRaw;
  stdin.setRawMode?.(true);
  stdin.resume();

  let value = "";

  try {
    while (true) {
      const chunk = await readStdinChar();
      const code = chunk.charCodeAt(0);

      if (chunk === "\u0003") {
        process.stdout.write("\n");
        throw new Error("Setup cancelled.");
      }

      if (chunk === "\r" || chunk === "\n") {
        process.stdout.write("\n");
        break;
      }

      if (chunk === "\u007f" || chunk === "\b") {
        if (value.length > 0) {
          value = value.slice(0, -1);
          process.stdout.write("\b \b");
        }
        continue;
      }

      value += chunk;
      process.stdout.write("•");
    }
  } finally {
    if (!wasRaw) {
      stdin.setRawMode?.(false);
    }
  }

  if (!allowEmpty && !value.trim()) {
    return readMaskedFromTty(label, { allowEmpty });
  }

  return value;
}

function readStdinChar() {
  return new Promise((resolve, reject) => {
    const onReadable = () => {
      const chunk = process.stdin.read(1);
      if (chunk) {
        cleanup();
        resolve(chunk.toString("utf8"));
      }
    };

    const onError = (error) => {
      cleanup();
      reject(error);
    };

    const cleanup = () => {
      process.stdin.off("readable", onReadable);
      process.stdin.off("error", onError);
    };

    process.stdin.on("readable", onReadable);
    process.stdin.on("error", onError);
  });
}